Functional programming. Problems resolved via it.
Marchenkos/Task_js pull request #3
Opened 2019-09-04 21:19 UTC by Marchenkos

In this task problems are solved using: partial application, currying, linear fold, lazy evaluation, memoization, inheritance and function with any number of parameters.

2019-09-05 06:01 UTC, AntonPashkowskiy requested changes

2019-09-05 06:01 UTC, AntonPashkowskiy commented on functional_progamming.js
> +    return (hight, radius) => {
Это частный случай partial application. Тебе нужно написать функцию которая будет универсальной. Например будет убирать первые n параметров функции. Для этого можно скомпоновать замыкание, тем что arguments хранит в себе все переданные функции параметры и тем что можно выполнить функцию с массивом её параметров через apply.

2019-09-05 06:01 UTC, AntonPashkowskiy commented on functional_progamming.js
> +function cury(action) {
curry

2019-09-05 06:01 UTC, AntonPashkowskiy commented on functional_progamming.js
> +                return action(param1, param2, param3);
опять же, частный случай. нужна функция которая будет возвращать функцию принимающую следующий аргумент, и выполняющую целевую функцию когда этих аргументов достаточно. для того что бы понять что их достаточно можно передать ожидаемое количество аргументов.

2019-09-05 06:01 UTC, AntonPashkowskiy commented on functional_progamming.js
> +    let newArray = [];
Задание немного некорректно, но это можно было почитать в самом функциональном программировании. Суть в том что для начала нужно было реализовать свёртку. А map, filter и average реализовать уже через эту свёртку. То что ты умеешь их написать просто так я уже знаю.

2019-09-05 06:01 UTC, AntonPashkowskiy commented on functional_progamming.js
> +        let mem = memoize(action);
mem -> memoizedAction

2019-09-05 06:01 UTC, AntonPashkowskiy commented on functional_progamming.js
> +        newArray.push(key);
отступ

2019-09-05 06:01 UTC, AntonPashkowskiy commented on functional_progamming.js
> +let lazyFunction = function(array, n, action) {
по имени параметра array не понятно для чего он нужен

2019-09-05 06:01 UTC, AntonPashkowskiy commented on functional_progamming.js
> +    for(let i = 0; i < arguments.length - 1; i++) {
arguments хранит в себе параметры функции, вот они, сверху. этот массив нужен если функция принимает заранее неизвестное количество параметров. скопировать его можно вызвав `Array.prototype.slice.call(null, array)`

2019-09-05 06:01 UTC, AntonPashkowskiy commented on functional_progamming.js
> +    return action.apply(this, arrayPar);
и это не ленивая функция. она же сразу отдаёт мне результат. а я хочу функцию которая при вызове выдаст мне результат.
```js
let lazyAction = lazy(action, parameters)

lazyAction() === action(parameters)
```

2019-09-05 06:01 UTC, AntonPashkowskiy commented on functional_progamming.js
> +    calculateArea(height, width) {
у тебя height и width будут свойствами класса. зачем их принимать как параметры?

2019-09-05 06:01 UTC, AntonPashkowskiy commented on functional_progamming.js
> +        return height * width;
реализация этого метода в базовом классе не нужна. нет никакого общего способа посчитать площадь разных фигур.

2019-09-05 06:01 UTC, AntonPashkowskiy commented on functional_progamming.js
> +        return height * width;
можно оставить метод пустым, что бы было видно интерфейс.

2019-09-05 06:01 UTC, AntonPashkowskiy commented on functional_progamming.js
> +        let areaValue = 0;
Я сначала думал что это какая-то ошибка, задача ведь на понимание полиморфизма, то есть использования интерфейса независимо от реализации. А потом перечитал задание и понял что не понимает для чего эта задача в первую очередь человек который её составил. Оставь один метод area, который посчитает сумму площадей всех фигур вне зависимости от того что за они. Добавь в иерархию наследования круг с необходимыми параметрами, что бы было ещё нагляднее.

2019-09-05 13:13 UTC, AntonPashkowskiy requested changes

2019-09-05 13:13 UTC, AntonPashkowskiy commented on tasks.js
> +    return (...arguments) => {
этот аргумент не используется. arguments и так есть у каждой ф-ии

2019-09-05 13:13 UTC, AntonPashkowskiy commented on functional_progamming.js
> +            areaValue = areaValue + this.shapesArray[i].calculateArea();
можешь воспользоваться своим же reduce - получится меньше кода

2019-09-06 05:43 UTC, AntonPashkowskiy requested changes

2019-09-06 05:43 UTC, AntonPashkowskiy commented on lazy.js
> +        newArray.push(key);
Отступ! :)

2019-09-06 05:43 UTC, AntonPashkowskiy commented on lazy.js
> +    let arrayPar = Array.prototype.slice.call(arguments, 1);
arrayOfParameters

2019-09-06 05:43 UTC, AntonPashkowskiy commented on mapFiltAver.js
> +        if(newArray[i] == true) {
Так писать не очень правильно, потому что if сам по себе проверяет значение на true\false. достаточно было бы просто `if(newArray[i])`. Но это всё равно не имеет смысла так как не понятно зачем тебе тут folding. Фильтр это просто свётка исходного массива с помощью функции которая будет добавлять в пустой массив значения только если они удовлетворяют предикату.

2019-09-06 05:43 UTC, AntonPashkowskiy commented on mapFiltAver.js
> +        if(newArray[i] == true) {
То есть фильтр можно реализовать только с помощью свёртки.

2019-09-06 05:43 UTC, AntonPashkowskiy commented on mapFiltAver.js
> +    return retunAray;
Такую переменную, если бы она была нужна, стоило бы назвать result.

2019-09-06 05:43 UTC, AntonPashkowskiy commented on mapFiltAver.js
> +        newArray.push(lastValue);
Ага, вот и вскрылась причина проблем в предыдущих функциях. Свётка это немного другое. У тебя есть массив значений и функция, которая принимает последовательно все значения из массива и значение-аккумулятор, при этом изменяя аккумулятор каждым последующим значением. А у тебя почему-то всегда массив получается.

```js
accumulator = foldingFunction(accumulator, array[i])
```

и с таким раскладом нам совершенно без разницы что такое этот аккумулятор, а foldingFunction мы можем передать такой какой захотим. и реализовать тупо на нём и map и filter и average

2019-09-06 05:43 UTC, AntonPashkowskiy commented on tasks.js
> +function applyPartial(action, n) {
я вчера не обратил на это внимание. но я сейчас совсем не понимаю что делает эта функция. она должна принимать action, и один\массив его параметров. вернуть функцию, как ты правильно сделала, и сделать apply тех параметров что передали и тех что придут следом.

2019-09-06 05:43 UTC, AntonPashkowskiy commented on functional_progamming.js
> +        parameters = argms[0];
зачем делать такое разделение, если можно просто написать `let parameters = arguments[0]`

2019-09-06 05:43 UTC, AntonPashkowskiy commented on functional_progamming.js
> +function applyPartial(action, n) {
почему у тебя одинаковые функции в разных файлах?

2019-09-06 10:09 UTC, Marchenkos commented on mapFiltAver.js
> +        newArray.push(lastValue);
Но мне же нужно возвращать разные вещи: массив для map и filter и переменную ( которая и будет равна accumulator) для average.

2019-09-06 12:47 UTC, AntonPashkowskiy requested changes

2019-09-06 12:47 UTC, AntonPashkowskiy commented on functional_progamming.js
> +    return (...argms) => {
args если уж очень нужно. выдерживай сокращения хотя бы в рамках одного файла. но вообще старайся их избегать.

2019-09-06 12:47 UTC, AntonPashkowskiy commented on functional_progamming.js
> +    return (action1) => {
action1 -> filterFunction, action2 -> averageAction. вообще не понимаю зачем ты возвращаешь функцию. ты должна была просто использовать тот average и filter что уже написала.

2019-09-06 12:47 UTC, AntonPashkowskiy commented on functional_progamming.js
> +    let arrayOfPar = Array.prototype.slice.call(arguments, 1);
arrayOfParameters. что ты будешь делать со всем этим сэкономленным временем!?

2019-09-06 12:47 UTC, AntonPashkowskiy commented on functional_progamming.js
> +    let arrayOfPar = Array.prototype.slice.call(arguments, 1);
ни читать неудобно, потому что как будто глазами спотыкаешься об этот par, ни вспоминать потом по ходу работы что там у тебя было за сокращение.

2019-09-06 12:47 UTC, AntonPashkowskiy commented on functional_progamming.js
> +        let mult = 1;
mult -> result. argms -> args

2019-09-06 13:06 UTC, AntonPashkowskiy approved these changes

2019-09-06 13:06 UTC, merged